task 7 done
kellysum/nc-news-server pull request #7
Opened 2023-11-22 12:24 UTC by kellysum

2023-11-22 12:31 UTC, nc-jonathan-mcguire requested changes
Just a few changes to make please and a test to add:

- [ ] Status 400: Bad request, incomplete body - Request body incomplete/missing required field(s) of username or body.

Please see my comments for other changes needed

2023-11-22 12:31 UTC, nc-jonathan-mcguire commented on __tests__/app.test.js
> +    test('400: responds with an error message if the article_id does not exist', ()=>{
should be article id is invalid

2023-11-22 12:31 UTC, nc-jonathan-mcguire commented on __tests__/app.test.js
> +    test('400: responds with an error message if the username does not exist', ()=>{
would be 404 - username not found - the request is valid, its just not found

2023-11-22 12:31 UTC, nc-jonathan-mcguire commented on controller/controller.js
> +    insertComment(newComment, article_id).then((postedComments)=>{
shoiuld only be one comment, so makes sense to call the key `comment`

2023-11-22 12:31 UTC, nc-jonathan-mcguire commented on model/comments.model.js
> +       console.log(data.rows[0])
remove log

2023-11-23 09:43 UTC, nc-verity-gregory approved these changes
Nicely done. Merge away!

2023-11-23 09:48 UTC, merged